#!/usr/bin/env python3

import csv
import sys
import time

class keyDataClass:
    def __init__(self, key, data):
        self.key = key
        self.data = data

def Merge(left, right):
    result = []
    while(len(left) > 0 and len(right) > 0):
        if left[0].key <= right[0].key:
            result.append(left.pop(0))
        else:
            result.append(right.pop(0))
    if left == []:
        result = result + right
    else:
        result = result + left
    return result

def Merge_Sort(A):
    if len(A) < 2:
        return A
    else:
        q = len(A)//2
        left=Merge_Sort(A[:q])
        right=Merge_Sort(A[q:])

    return Merge(left,right)
        
        
with open(sys.argv[1]) as file:
    csvreader = csv.reader(file)
    keyDataSet = []
    for row in csvreader:
        newKeyData = keyDataClass(int(row[0]), row[1:])
        keyDataSet.append(newKeyData)

    start = time.time()
    result = Merge_Sort(keyDataSet)
    end = time.time()

    for val in result:
        val.data.insert(0, str(val.key))
        print(val.data)

    print(end-start)