#!/usr/bin/env python3

import csv
import sys
import time

class keyDataClass:
    def __init__(self, key, data):
        self.key = key
        self.data = data

def partition(A, p, r):
    x = A[r].key
    i = p -1
    for j in range(p, r):
        if A[j].key <= x:
            i = i+1
            temp = A[i]
            A[i] = A[j]
            A[j] = temp
    temp2 = A[i+1]
    A[i+1] = A[r]
    A[r] = temp2
    return(i+1)

def quickSort(A, p, r):
    if p < r:
        q = partition(A, p ,r)
        quickSort(A, p, q-1)
        quickSort(A, q+1, r)

with open(sys.argv[1]) as file:
    csvreader = csv.reader(file)
    keyDataSet = []

    for row in csvreader:
        newKeyData = keyDataClass(int(row[0]), row[1:])
        keyDataSet.append(newKeyData)
   
    start = time.time()
    quickSort(keyDataSet, 0, len(keyDataSet)-1)
    end = time.time()

    for val in keyDataSet:
        val.data.insert(0, str(val.key))
        print(val.data)

    print(end-start)



