#!/usr/bin/env python3

import csv
import sys
import time

class keyDataClass:
    def __init__(self, key, data):
        self.key = key
        self.data = data

def bubbleSort(A):
    n = len(A)
    flag=0

    for i in range(n-1):
        for j in range(0, n-i-1):
            if A[j].key > A[j+1].key:
                A[j], A[j+1] = A[j+1], A[j]
                #temp = A[j]
                #A[j] = A[j+1]
                #A[j+1] = temp

        


with open(sys.argv[1]) as file:
    csvreader = csv.reader(file)
    keyDataSet = []
    for row in csvreader:
        newKeyData = keyDataClass(int(row[0]), row[1:])
        keyDataSet.append(newKeyData)

    start = time.time()
    bubbleSort(keyDataSet)
    end = time.time()

    for val in keyDataSet:
        val.data.insert(0, str(val.key))
        print(val.data)

    print(end-start)