#!/usr/bin/env python3

import csv
import sys
import time
import random

with open(sys.argv[1], 'a') as file:
    size = 100
    used = [[0]*size for i in range(size)]
    for i in range(0,size):
        for j in range(0, size):
            used[i][j] = 0
    for i in range(0, int(sys.argv[2])):
        taken = 1
        while(taken == 1):
            random_in = random.randint(0,99)
            random_out = random.randint(0,99)
            if used[random_in][random_out] != 1:
                weight = round(10*random.random(),8)
                line = str(random_in) + " " + str(random_out) + " " + str(weight)
                file.write(line)
                file.write('\n')
                taken = 0
                used[random_in][random_out] = 1

    count = 0
    for i in range(0,100):
        for j in range(0,100):
            if used[i][j] == 1:
                count +=1
    print(count)
